
#pragma once


#include "macros.h"
#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/classes/ref_counted.hpp>

namespace godot {

class Decoration;

class DecorationState : public Resource {
	DECLARE_CLASS(DecorationState, Resource);

	enum Direction {
		North, East, South, West
	};

    Ref<Decoration> decoration;
    Vector3i position;

	// Used by structure decorations that conditionally spawn cutscene blocks --
	// If true, a cutscene block must be generated by this decoration
	bool has_cutscene_block = false;

	Direction direction = North;

};

}